mutation schedule($type: String!, $interestRate: Float!, $loanAmount: Int!, $loanTerm: Int!) {
    schedule(
        input: {
            type: $type
            interestRate: $interestRate
            loanAmount: $loanAmount
            loanTerm: $loanTerm
        }
    ) {
        monthlyPayment
        interestDebtPay
        principalDebtPay
        monthlyLoanAmount
    }
}
