mutation {
    schedule(
        input: {
            type: "$type"
            interestRate: $interestRate
            loanAmount: $loanAmount
            loanTerm: $loanTerm
        }
    ) {
        monthlyPayment
        interestDebtPay
        principalDebtPay
        monthlyLoanAmount
    }
}
